### ISSUE TITLE
InvalidProgramException occurs when attempting to access Postgres db using Npgsql

### ISSUE THREAD

**Issue by williamwilson** [signalfx/signalfx-dotnet-tracing#79]
**Describe the bug**
A couple of the services that we're instrumenting using signalfx-dotnet-tracing are throwing InvalidProgramExceptions when attempting to open connections and/or read from the database using npgsql.

I believe this is the same issue reported in the upstream (for which the fix has not been pulled into this fork):
https://github.com/DataDog/dd-trace-dotnet/issues/762
and the subsequent fix:
https://github.com/DataDog/dd-trace-dotnet/pull/875

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Npgsql.PostgresDatabaseInfo.LoadBackendTypes(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Npgsql.PostgresDatabaseInfo.LoadBackendTypes(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.PostgresDatabaseInfo.LoadPostgresInfo(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.PostgresDatabaseInfoFactory.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlDatabaseInfo.Load(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.LoadDatabaseInfo(NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
```

**To Reproduce**
Unfortunately, due to the nature of this bug, I don't have a reliable means of reproducing this issue.

**Expected behavior**
Valid IL is produced by instrumentation which avoids the InvalidProgramException.

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual install on linux
- Tracer version: 0.1.1
- OS: alpine 3.12
- CLR: .NET Core 3.1

**Additional context**

**Comment by pjanotti** [comment]
Thanks @williamwilson for the detailed report and the links to the likely cause. I didn't have luck with a toy-sized repro. Could you please try the image from this PR? Please, let's know how it goes.

https://app.circleci.com/pipelines/github/signalfx/signalfx-dotnet-tracing/208/workflows/41647c3f-73fe-4dd6-9f21-c329964b649a/jobs/269/artifacts

**Comment by williamwilson** [comment]
Thanks.  I'm testing it now.

**Comment by williamwilson** [comment]
@pjanotti Is that the correct link?  That appears to be a build from 21 days ago, should I be using https://app.circleci.com/pipelines/github/signalfx/signalfx-dotnet-tracing/210/workflows/cfdae0d1-092a-483e-a0bc-2bc37d1a6f52/jobs/278/artifacts instead?

**Comment by pjanotti** [comment]
Sorry about that @williamwilson , you got the correct link, the one that I posted above was incorrect - thanks for catching that!

**Comment by williamwilson** [comment]
No worries.  We've been running it all day with no InvalidProgramExceptions so far.  I'd like to monitor it for a day or two before feeling confident it's fixed given the nature of this issue.

**Comment by williamwilson** [comment]
We've been running this for a few days now without seeing any InvalidProgramExceptions.  We were seeing one about every four hours on average before, so I am confident in saying that this has resolved the issue.

**Comment by pjanotti** [comment]
Thanks @williamwilson for all your help with this issue. We will publish a new official release including the fix in the next few days.
